version: '3.9'
services:
  manager-backend:
    image: docker-manager-image:0.0.1
    build:
      context: ./Manager
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - my-database
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://my-database/postgres

  restapi-backend:
    image: docker-rest-image:0.0.1
    build:
      context: ./demo1
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - my-database
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://my-database/postgres

  my-database:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db-data:
  pgadmin-data:
