spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: postgres
    password: admin
  jpa:
    show-sql: true
  flyway:
    schemas:
      - user_management

server:
  port: ${SERVER_PORT}

logging:
  level:
    sql: info

users:
  service:
    list:
      uri: "http://192.168.1.67:8081"
    username: Superuser
    password: admin